### PR TITLE
Extend documentation

### PR DESCRIPTION
**Pull request by paultcochrane**
Hi Liz!

This PR adds some quick installation and development docs so that newcomers can quickly see how to install the module and anyone who wants to help with development can see how to install dependencies and run the test suite.  I've also bumped the copyright year to match the current year (assuming that this PR gets submitted ;-) ).  I also noticed that the name of the main program had been changed and I've updated the docs to reflect this.

As usual, if you want anything changed with this PR, please just let me know and I'll be more than happy to fix things and resubmit.

Say hello to Wendy from me!

Cheers,

Paul

### CODE REVIEW

**Comment by lizmat** [comment]
@paultcochrane Thanks for the PR.  The effort is appreciated!

Note that for all my modules, the README.md is generated from the pod by `App::Mi6`.  The pod either lives in the source file if it is a smallish module, or in a separate file in the `doc` directory.  So any changes should be done there, and if you have `App::Mi6` installed, a `mi6 build` will re-generate the README.md.

Also, I usually do **not** mention the installation boilerplate.  This maybe lazy of me, but the installation boiler plate has changed over the years, and very well may change in the future as well.  So I'd rather assume that any user of the module will find that boiler plate.  Or maybe a site such as raku.land could have a generic boilerplate.

**Comment by lizmat** [comment]
So, if you could remove the boilerplate, and do the changes in the pod, that would be brill!

Also, perhaps better to do 2021, 2024 as nothing happened to that source in 2022, 2023.

**Comment by paultcochrane** [comment]
Hi @lizmat. Sorry, I should have realised that the pod is automatically generated. We've been here before :-/  I'll remove the installation boilerplate, and fix up the other commits that's no problem :-)  From a user perspective, I've always found such information useful directly in the README, hence why I often propose such changes.

Just wondering: would perhaps a link to an appropriate documentation page be a better idea?  I mean, I've been quite familiar with Raku in the past and it took me a while to find the correct invocations again; a link to a definitive installation source might reduce the friction for newcomers and mean that you don't have to add installation boilerplate to all of your modules.  Just an idea!

**Comment by lizmat** [comment]
I would welcome a link for installation instructions.  But I wouldn't know where to link to?

**Comment by paultcochrane** [comment]
> Also, perhaps better to do 2021, 2024 as nothing happened to that source in 2022, 2023.

Looking at the git history, there are commits from 2022 and 2023.  There were also releases in 2022.  Thus, I think it's fair to say that the copyright spans 2021 up to and including 2024 (assuming this patch gets merged).  I'll set the copyright years how you want, but I think the range is still accurate.  If you change your mind, let me know and I'll update the PR :-)

**Comment by paultcochrane** [comment]
I've updated the commits and have force-pushed the feature branch.  Let me know what you think!

**Comment by lizmat** [comment]
Ok, 2021 - 2024 it is then  :-)

**Comment by lizmat** [comment]
Thanks!

**Pull request merged**
